package com.example.learningagent.agent;

public enum LearningTrack {
    JAVA, JAVA_COLLECTIONS, JAVA_CONCURRENCY, JVM, SPRING,
    COMPUTER_SCIENCE, DATA_STRUCTURES, OPERATING_SYSTEMS, COMPUTER_NETWORKS,
    ARCHITECTURE, DATABASE, DISTRIBUTED_SYSTEMS,
    REDIS, KAFKA, ROCKETMQ,
    AI, MACHINE_LEARNING, LLM, RAG, AI_AGENT, AI_TOOLS, MODEL_UPDATES
}
